[build]
command = "npm run build"

[functions]
directory = "netlify/functions/"
external_node_modules = ["express"]
node_bundler = "esbuild"

[[redirects]]
force = true
from = "/*"
to = "/netlify/functions/server"
status = 200